server {
    listen 80;
    listen [::]:80;

    server_name webhook.voidpresence.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name webhook.voidpresence.com;

    ssl_certificate /etc/letsencrypt/live/webhook.voidpresence.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/webhook.voidpresence.com/privkey.pem;

    client_max_body_size 1m;

    location / {
        limit_req zone=webhook_limit burst=10 nodelay;
        limit_conn webhook_conn 10;

        proxy_pass http://backend-webhook:8080;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
